### ISSUE TITLE
另一套EFI

### ISSUE THREAD

**Issue by ldy5413** [c1awn/hackintosh-Lenovo-E431#1]
[Files Needed e431.zip](https://github.com/c1awn/hackintosh-Lenovo-E431/files/4585428/Files.Needed.e431.zip)
我也在用e431 i5-3320m, 这套EFI 是我在网上找的，用于14.6，感觉比你的快一点，也没有花屏，不足之处在于无法看到电池，并且装了smart touchpad那个kext后触控板的设置点进去为空白，其余感觉没啥缺点。你可以尝试一下。

**Comment by c1awn** [comment]
感谢，e431还是太老了，不折腾它了。
