### ISSUE TITLE
hdmi外接电视不能输出声音

### ISSUE THREAD

**Issue by Phe2703** [c1awn/hackintosh-Lenovo-E431#2]
在15.5和14.6都试了，只能使用本机扬声器，我想确认下是这个efi的确不能输出声音吗，还是我少了哪个环节

**Comment by c1awn** [comment]
> 在15.5和14.6都试了，只能使用本机扬声器，我想确认下是这个efi的确不能输出声音吗，还是我少了哪个环节

Hdmi是没声音…这个hdmi无声好像是个未解决的问题。你可以搜下，共性问题。

**Comment by Phe2703** [comment]
> 
> 
> > 在15.5和14.6都试了，只能使用本机扬声器，我想确认下是这个efi的确不能输出声音吗，还是我少了哪个环节
> 
> Hdmi是没声音…这个hdmi无声好像是个未解决的问题。你可以搜下，共性问题。

好的，感谢分享😁
